SELECT * FROM customers limit 10;
#HERE We are try to give the answers of this questions.

-- 1.What is the  total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) as revenue from customers group by gender;

-- 2.Which customers used a discount but still spent more than the average purchase Amount?
select customer_id,purchase_amount
from customers where discount_applied = 'yes' 
and purchase_amount >=(select Avg(purchase_amount) from customers);
-- 3.Which are the top 5 products with the highest average review rating?
select item_purchased,avg(review_rating)as "Average_product_Rating"
from customers
group by item_purchased
order by avg(review_rating) desc limit 5;

-- 4.Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type,
ROUND(AVG(purchase_amount), 2)
FROM customers
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;
-- 5.Do subscribe customers spend more?compare Average spend and total revenue between subsribers and non-subscribers.
select subscription_status,
count(customer_id) AS total_customers,
ROUND(AVG(Purchase_amount),2)as avg_spend,
ROUND(sum(purchase_amount),2)as total_revenue
from customers
group by subscription_status order by total_revenue DESC,avg_spend desc;

-- 6.which 5 products have the highest percentage of purchase with discount applied?
SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) 
      / COUNT(*), 2) AS discount_rate
FROM customers
GROUP BY item_purchased
ORDER BY discount_rate DESC limit 10;
-- 7.Segment customers into new,returning,and loyal based on their total number of previous purchases,and
WITH customer_type as
(select customer_id,previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'new'
    WHEN previous_purchases between 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
    from customers
)
select customer_segment,count(*) as "number of customers"
from customer_type
group by customer_segment;

-- 8.what are the top 3 most purchased products within each category?
WITH item_count AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customers
    GROUP BY category, item_purchased
)

SELECT 
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_count
WHERE item_rank <= 3;

-- 9. Are customers who are repeat buyers (more than 5 previous ourchases) also likely to subscribes?

select subscription_status,
count(customer_id) as repeat_buyers
from customers
where previous_purchases >5
group by subscription_status;

-- 10. What is the revenue contribution of each age group?
select age_group,
SUM(purchase_amount) as total_revenue
from customers
group by age_group
order by total_revenue DESC;






